<audio title="19 _ 错误处理（上）" src="https://static001.geekbang.org/resource/audio/87/ef/8721ac7cd9292553db302c15cb996bef.mp3" controls="controls"></audio> 
<p>提到Go语言中的错误处理，我们其实已经在前面接触过几次了。</p><p>比如，我们声明过<code>error</code>类型的变量<code>err</code>，也调用过<code>errors</code>包中的<code>New</code>函数。今天，我会用这篇文章为你梳理Go语言错误处理的相关知识，同时提出一些关键问题并与你一起探讨。</p><p>我们说过<code>error</code>类型其实是一个接口类型，也是一个Go语言的内建类型。在这个接口类型的声明中只包含了一个方法<code>Error</code>。<code>Error</code>方法不接受任何参数，但是会返回一个<code>string</code>类型的结果。它的作用是返回错误信息的字符串表示形式。</p><p>我们使用<code>error</code>类型的方式通常是，在函数声明的结果列表的最后，声明一个该类型的结果，同时在调用这个函数之后，先判断它返回的最后一个结果值是否“不为<code>nil</code>”。</p><p>如果这个值“不为<code>nil</code>”，那么就进入错误处理流程，否则就继续进行正常的流程。下面是一个例子，代码在demo44.go文件中。</p><pre><code>package main

import (
	&quot;errors&quot;
	&quot;fmt&quot;
)

func echo(request string) (response string, err error) {
	if request == &quot;&quot; {
		err = errors.New(&quot;empty request&quot;)
		return
	}
	response = fmt.Sprintf(&quot;echo: %s&quot;, request)
	return
}

func main() {
	for _, req := range []string{&quot;&quot;, &quot;hello!&quot;} {
		fmt.Printf(&quot;request: %s\n&quot;, req)
		resp, err := echo(req)
		if err != nil {
			fmt.Printf(&quot;error: %s\n&quot;, err)
			continue
		}
		fmt.Printf(&quot;response: %s\n&quot;, resp)
	}
}
</code></pre><p>我们先看<code>echo</code>函数的声明。<code>echo</code>函数接受一个<code>string</code>类型的参数<code>request</code>，并会返回两个结果。</p><p>这两个结果都是有名称的，第一个结果<code>response</code>也是<code>string</code>类型的，它代表了这个函数正常执行后的结果值。</p><p>第二个结果<code>err</code>就是<code>error</code>类型的，它代表了函数执行出错时的结果值，同时也包含了具体的错误信息。</p><!-- [[[read_end]]] --><p>当<code>echo</code>函数被调用时，它会先检查参数<code>request</code>的值。如果该值为空字符串，那么它就会通过调用<code>errors.New</code>函数，为结果<code>err</code>赋值，然后忽略掉后边的操作并直接返回。</p><p>此时，结果<code>response</code>的值也会是一个空字符串。如果<code>request</code>的值并不是空字符串，那么它就为结果<code>response</code>赋一个适当的值，然后返回，此时结果<code>err</code>的值会是<code>nil</code>。</p><p>再来看<code>main</code>函数中的代码。我在每次调用<code>echo</code>函数之后，都会把它返回的结果值赋给变量<code>resp</code>和<code>err</code>，并且总是先检查<code>err</code>的值是否“不为<code>nil</code>”，如果是，就打印错误信息，否则就打印常规的响应信息。</p><p>这里值得注意的地方有两个。第一，在<code>echo</code>函数和<code>main</code>函数中，我都使用到了卫述语句。我在前面讲函数用法的时候也提到过卫述语句。简单地讲，它就是被用来检查后续操作的前置条件并进行相应处理的语句。</p><p>对于<code>echo</code>函数来说，它进行常规操作的前提是：传入的参数值一定要符合要求。而对于调用<code>echo</code>函数的程序来说，进行后续操作的前提就是<code>echo</code>函数的执行不能出错。</p><blockquote>
<p><span class="reference">我们在进行错误处理的时候经常会用到卫述语句，以至于有些人会吐槽说：“我的程序满屏都是卫述语句，简直是太难看了！”</span></p>
<p><span class="reference">不过，我倒认为这有可能是程序设计上的问题。每个编程语言的理念和风格几乎都会有明显的不同，我们常常需要顺应它们的纹理去做设计，而不是用其他语言的编程思想来编写当下语言的程序。</span></p>
</blockquote><p>再来说第二个值得注意的地方。我在生成<code>error</code>类型值的时候，用到了<code>errors.New</code>函数。</p><p>这是一种最基本的生成错误值的方式。我们调用它的时候传入一个由字符串代表的错误信息，它会给返回给我们一个包含了这个错误信息的<code>error</code>类型值。该值的静态类型当然是<code>error</code>，而动态类型则是一个在<code>errors</code>包中的，包级私有的类型<code>*errorString</code>。</p><p>显然，<code>errorString</code>类型拥有的一个指针方法实现了<code>error</code>接口中的<code>Error</code>方法。这个方法在被调用后，会原封不动地返回我们之前传入的错误信息。实际上，<code>error</code>类型值的<code>Error</code>方法就相当于其他类型值的<code>String</code>方法。</p><p>我们已经知道，通过调用<code>fmt.Printf</code>函数，并给定占位符<code>%s</code>就可以打印出某个值的字符串表示形式。</p><p>对于其他类型的值来说，只要我们能为这个类型编写一个<code>String</code>方法，就可以自定义它的字符串表示形式。而对于<code>error</code>类型值，它的字符串表示形式则取决于它的<code>Error</code>方法。</p><p>在上述情况下，<code>fmt.Printf</code>函数如果发现被打印的值是一个<code>error</code>类型的值，那么就会去调用它的<code>Error</code>方法。<code>fmt</code>包中的这类打印函数其实都是这么做的。</p><p>顺便提一句，当我们想通过模板化的方式生成错误信息，并得到错误值时，可以使用<code>fmt.Errorf</code>函数。该函数所做的其实就是先调用<code>fmt.Sprintf</code>函数，得到确切的错误信息；再调用<code>errors.New</code>函数，得到包含该错误信息的<code>error</code>类型值，最后返回该值。</p><p>好了，我现在问一个关于对错误值做判断的问题。我们今天的<strong>问题是：对于具体错误的判断，Go语言中都有哪些惯用法？</strong></p><p>由于<code>error</code>是一个接口类型，所以即使同为<code>error</code>类型的错误值，它们的实际类型也可能不同。这个问题还可以换一种问法，即：怎样判断一个错误值具体代表的是哪一类错误？</p><p>这道题的<strong>典型回答</strong>是这样的：</p><ol>
<li>对于类型在已知范围内的一系列错误值，一般使用类型断言表达式或类型<code>switch</code>语句来判断；</li>
<li>对于已有相应变量且类型相同的一系列错误值，一般直接使用判等操作来判断；</li>
<li>对于没有相应变量且类型未知的一系列错误值，只能使用其错误信息的字符串表示形式来做判断。</li>
</ol><h2>问题解析</h2><p>如果你看过一些Go语言标准库的源代码，那么对这几种情况应该都不陌生。我下面分别对它们做个说明。</p><p>类型在已知范围内的错误值其实是最容易分辨的。就拿<code>os</code>包中的几个代表错误的类型<code>os.PathError</code>、<code>os.LinkError</code>、<code>os.SyscallError</code>和<code>os/exec.Error</code>来说，它们的指针类型都是<code>error</code>接口的实现类型，同时它们也都包含了一个名叫<code>Err</code>，类型为<code>error</code>接口类型的代表潜在错误的字段。</p><p>如果我们得到一个<code>error</code>类型值，并且知道该值的实际类型肯定是它们中的某一个，那么就可以用类型<code>switch</code>语句去做判断。例如：</p><pre><code>func underlyingError(err error) error {
	switch err := err.(type) {
	case *os.PathError:
		return err.Err
	case *os.LinkError:
		return err.Err
	case *os.SyscallError:
		return err.Err
	case *exec.Error:
		return err.Err
	}
	return err
}
</code></pre><p>函数<code>underlyingError</code>的作用是：获取和返回已知的操作系统相关错误的潜在错误值。其中的类型<code>switch</code>语句中有若干个<code>case</code>子句，分别对应了上述几个错误类型。当它们被选中时，都会把函数参数<code>err</code>的<code>Err</code>字段作为结果值返回。如果它们都未被选中，那么该函数就会直接把参数值作为结果返回，即放弃获取潜在错误值。</p><p>只要类型不同，我们就可以如此分辨。但是在错误值类型相同的情况下，这些手段就无能为力了。在Go语言的标准库中也有不少以相同方式创建的同类型的错误值。</p><p>我们还拿<code>os</code>包来说，其中不少的错误值都是通过调用<code>errors.New</code>函数来初始化的，比如：<code>os.ErrClosed</code>、<code>os.ErrInvalid</code>以及<code>os.ErrPermission</code>，等等。</p><p>注意，与前面讲到的那些错误类型不同，这几个都是已经定义好的、确切的错误值。<code>os</code>包中的代码有时候会把它们当做潜在错误值，封装进前面那些错误类型的值中。</p><p>如果我们在操作文件系统的时候得到了一个错误值，并且知道该值的潜在错误值肯定是上述值中的某一个，那么就可以用普通的<code>switch</code>语句去做判断，当然了，用<code>if</code>语句和判等操作符也是可以的。例如：</p><pre><code>printError := func(i int, err error) {
	if err == nil {
		fmt.Println(&quot;nil error&quot;)
		return
	}
	err = underlyingError(err)
	switch err {
	case os.ErrClosed:
		fmt.Printf(&quot;error(closed)[%d]: %s\n&quot;, i, err)
	case os.ErrInvalid:
		fmt.Printf(&quot;error(invalid)[%d]: %s\n&quot;, i, err)
	case os.ErrPermission:
		fmt.Printf(&quot;error(permission)[%d]: %s\n&quot;, i, err)
	}
}
</code></pre><p>这个由<code>printError</code>变量代表的函数会接受一个<code>error</code>类型的参数值。该值总会代表某个文件操作相关的错误，这是我故意地以不正确的方式操作文件后得到的。</p><p>虽然我不知道这些错误值的类型的范围，但却知道它们或它们的潜在错误值一定是某个已经在<code>os</code>包中定义的值。</p><p>所以，我先用<code>underlyingError</code>函数得到它们的潜在错误值，当然也可能只得到原错误值而已。然后，我用<code>switch</code>语句对错误值进行判等操作，三个<code>case</code>子句分别对应我刚刚提到的那三个已存在于<code>os</code>包中的错误值。如此一来，我就能分辨出具体错误了。</p><p>对于上面这两种情况，我们都有明确的方式去解决。但是，如果我们对一个错误值可能代表的含义知之甚少，那么就只能通过它拥有的错误信息去做判断了。</p><p>好在我们总是能通过错误值的<code>Error</code>方法，拿到它的错误信息。其实<code>os</code>包中就有做这种判断的函数，比如：<code>os.IsExist</code>、<code>os.IsNotExist</code>和<code>os.IsPermission</code>。命令源码文件demo45.go中包含了对它们的应用，这大致跟前面展示的代码差不太多，我就不在这里赘述了。</p><h2>总结</h2><p>今天我们一起初步学习了错误处理的内容。我们总结了错误类型、错误值的处理技巧和设计方式，并一起分享了Go语言中处理错误的最基本方式。由于错误处理的内容分为上下两篇，在下一次的文章中，我们会站在建造者的角度，一起来探索一下：怎样根据实际情况给予恰当的错误值。</p><h2>思考题</h2><p>请列举出你经常用到或者看到的3个错误类型，它们所在的错误类型体系都是怎样的？你能画出一棵树来描述它们吗？</p><p>感谢你的收听，我们下期再见。</p><p><a href="https://github.com/hyper0x/Golang_Puzzlers">戳此查看Go语言专栏文章配套详细代码。</a></p><p></p>
<style>
    ul {
      list-style: none;
      display: block;
      list-style-type: disc;
      margin-block-start: 1em;
      margin-block-end: 1em;
      margin-inline-start: 0px;
      margin-inline-end: 0px;
      padding-inline-start: 40px;
    }
    li {
      display: list-item;
      text-align: -webkit-match-parent;
    }
    ._2sjJGcOH_0 {
      list-style-position: inside;
      width: 100%;
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      margin-top: 26px;
      border-bottom: 1px solid rgba(233,233,233,0.6);
    }
    ._2sjJGcOH_0 ._3FLYR4bF_0 {
      width: 34px;
      height: 34px;
      -ms-flex-negative: 0;
      flex-shrink: 0;
      border-radius: 50%;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 {
      margin-left: 0.5rem;
      -webkit-box-flex: 1;
      -ms-flex-positive: 1;
      flex-grow: 1;
      padding-bottom: 20px;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 ._2zFoi7sd_0 {
      font-size: 16px;
      color: #3d464d;
      font-weight: 500;
      -webkit-font-smoothing: antialiased;
      line-height: 34px;
    }
    ._2sjJGcOH_0 ._36ChpWj4_0 ._2_QraFYR_0 {
      margin-top: 12px;
      color: #505050;
      -webkit-font-smoothing: antialiased;
      font-size: 14px;
      font-weight: 400;
      white-space: normal;
      word-break: break-all;
      line-height: 24px;
    }
    ._2sjJGcOH_0 ._10o3OAxT_0 {
      margin-top: 18px;
      border-radius: 4px;
      background-color: #f6f7fb;
    }
    ._2sjJGcOH_0 ._3klNVc4Z_0 {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      -webkit-box-pack: justify;
      -ms-flex-pack: justify;
      justify-content: space-between;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      margin-top: 15px;
    }
    ._2sjJGcOH_0 ._10o3OAxT_0 ._3KxQPN3V_0 {
      color: #505050;
      -webkit-font-smoothing: antialiased;
      font-size: 14px;
      font-weight: 400;
      white-space: normal;
      word-break: break-word;
      padding: 20px 20px 20px 24px;
    }
    ._2sjJGcOH_0 ._3klNVc4Z_0 {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      -webkit-box-pack: justify;
      -ms-flex-pack: justify;
      justify-content: space-between;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      margin-top: 15px;
    }
    ._2sjJGcOH_0 ._3Hkula0k_0 {
      color: #b2b2b2;
      font-size: 14px;
    }
</style><ul><li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/11/69/b5/1e1731cc.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>zs阿帅</span>
  </div>
  <div class="_2_QraFYR_0">go2设计草案里提到说对于这种error处理的多个卫术语句的简化，利用check，handler简化错误处理的代码量。</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2018-09-24 11:10:13</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/0f/8e/b0/ef201991.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>CcczzZ</span>
  </div>
  <div class="_2_QraFYR_0">之前要模板化的方式生成错误信息，都会用 errors.New() + fmt.Sprintf() 的组合去生成错误信息， errors.New(fmt.Sprintf())。<br>看完文章之后发现还有 fmt.Errorf函数 可直接模版话方式生成错误信息，方便不少，开心😄之前的方式真是不太优雅</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-01-09 14:39:29</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJAWUhO0xSjD6wbGScY5WOujAE94vNYWlWmsVdibb0IWbXzSSNXJHp0lqfWVq8ZicKBsEY1EuAWArew/132"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Felix</span>
  </div>
  <div class="_2_QraFYR_0">老师，我一直想知道关于io.EOF怎么理解，拿文件来说如果文件读取结束后，为什么是EOF结束，或者说到底什么是EOF.</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: EOF 就是 End Of File 的缩写。早在 Unix 操作系统诞生之初就有 EOF 这种形式了，它最早象征着文件中内容的结束。由于一些原因，它被很多操作系统和编程语言沿用了。现在的 EOF 的用途已经远不止表示文件的末尾了，它在很多地方都表示某种数据流的末尾。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-04-07 22:45:14</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/10/5b/66/ad35bc68.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>党</span>
  </div>
  <div class="_2_QraFYR_0">打卡 已经看了快2&#47;5了 因为之前学过 只是会用 没有这么深入了解过 这次 很多知识点都有新的认识了 </div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-07-27 08:20:20</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/0f/57/f1/a6e4770a.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>那句诺言</span>
  </div>
  <div class="_2_QraFYR_0">老师，“该值的静态类型当然是error，而动态类型则是一个在errors包中的，包级私有的类型*errorString”，静态类型和动态类型该怎么理解呢？</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 我讲接口的时候讲了啊。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2018-10-30 17:39:45</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/1e/96/3a/e06f8367.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>胡小涵</span>
  </div>
  <div class="_2_QraFYR_0">郝老师您好，抱歉最近刚看到18年关于您近况的文章，想问一下您最近怎么样了？身体还好嘛？祝老师身体健康！平安顺遂！</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 现在算是稳定了，或者说基本达到了另外一种平衡状态。谢谢关心：）</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-04-27 15:51:08</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/13/09/22/22c0c4fa.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>benying</span>
  </div>
  <div class="_2_QraFYR_0">评论的人很少了，打卡，20190605</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-06-05 16:21:33</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/14/ce/b2/1f914527.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>海盗船长</span>
  </div>
  <div class="_2_QraFYR_0">go1.13中，errors又新增了3个方法 <br>errors.Unwrap <br>errors.Is <br>errors.As</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-11-26 20:57:43</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/14/ce/b2/1f914527.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>海盗船长</span>
  </div>
  <div class="_2_QraFYR_0">老师你好，在代码中如何优雅地处理错误呀，有没有办法 不需要在每个方法中处理，集中到一个地方处理？</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 基本上是这样，就拿Web系统来说，一般情况下会在系统的最上层（接收request的那一层）统一处理错误。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-03-15 17:07:46</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/0f/4a/96/99466a06.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Laughing</span>
  </div>
  <div class="_2_QraFYR_0">常用到的net和json包中的错误类型有：<br>1. AddrError <br>2. SyntaxError<br>3. MarshalerError<br></div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2018-10-06 10:57:15</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/12/45/31/53910b61.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>A 凡</span>
  </div>
  <div class="_2_QraFYR_0">感觉第一遍看的时候，看的不够仔细，所以从头有看到这部分，发现细节性的东西还是有很多需要注意！</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2018-10-24 13:19:19</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/15/e8/55/92f82281.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>MClink</span>
  </div>
  <div class="_2_QraFYR_0">echo 函数 return 后面的东西呢？</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 因为那个函数存在有名称的结果声明，所以在该函数开始执行的时候，作为其结果的变量（如 echo 函数中的 response 变量和 err 变量）就已经自动创建好了。因此，这种函数中的 return 就可以不加任何东西，这时返回的就是那几个结果变量（如 response 和 err）的值。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-03-20 10:51:06</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/12/97/c5/84491beb.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>罗峰</span>
  </div>
  <div class="_2_QraFYR_0">两个err 比较，应该是比较 相应的动态类型以及动态值是不是 完全一样，感觉就是地址的比较把</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 是的。不过修正下你说的话，是“两个 error 类型值的比较”，不是“两个 err 比较”。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-06-06 09:34:05</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/12/5e/7a/028dc1a9.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>修罗</span>
  </div>
  <div class="_2_QraFYR_0">打卡</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2020-03-01 14:23:35</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/qhonwcQle1RBufvLdTm4MgSNl554GBXUZtNNH65oYajbbRLxKsZX4hM9vFtrLLpDM0H93ZNWRFAZSrIZC7yAsQ/132"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Geek_as</span>
  </div>
  <div class="_2_QraFYR_0">underlyingError函数我还是有点懵逼，多个switch全部都是执行err.Err，那不需要switch直接执行不也可以吗</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 这里的underlyingError函数的意思是，参数err的类型只要是*os.PathError、*os.LinkError、*os.SyscallError或*exec.Error中的任意一个的话，就返回err内含的（也就是潜在的）那个错误，否则就把参数err原封不动地返回去。函数如其名，它就是要设法拿到原错误的潜在错误。<br><br>当然，你也可以把那些用于判断的类型写到一个case里。我这里是为了在文章中清晰展示，所以把它们分开写了。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2022-04-19 14:37:13</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/21/63/6e/6b971571.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Z宇锤锤</span>
  </div>
  <div class="_2_QraFYR_0">boundsError越界异常</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2022-04-08 19:49:26</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src=""
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>Geek_05d654</span>
  </div>
  <div class="_2_QraFYR_0">type PathError struct {<br>	Op   string<br>	Path string<br>	Err  error<br>}<br><br>func (e *PathError) Error() string { return e.Op + &quot; &quot; + e.Path + &quot;: &quot; + e.Err.Error() }</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2022-03-03 11:00:00</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKELX1Rd1vmLRWibHib8P95NA87F4zcj8GrHKYQL2RcLDVnxNy1ia2geTWgW6L2pWn2kazrPNZMRVrIg/132"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>jxs1211</span>
  </div>
  <div class="_2_QraFYR_0">判断2个接口类型（比如这里error类型的值）的值是否相等，是否就是判断他们的的实际类型和实际值是否相等，验证一下认为不是这样比较的，不是的话，什么情况下是相等的呢</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 类型转换之后再比较啊，你可以用类型断言或者 type switch 语句去判断类型。但一般都会有 other（或者说 default）的情况，这需要妥善处理。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-12-01 23:11:48</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/15/5b/85/1d7abd78.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>任小龙</span>
  </div>
  <div class="_2_QraFYR_0">pkg&#47;errors，学习中。</div>
  <div class="_10o3OAxT_0">
    
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2021-05-27 07:33:33</div>
  </div>
</div>
</div>
</li>
<li>
<div class="_2sjJGcOH_0"><img src="https://static001.geekbang.org/account/avatar/00/12/7b/2a/7d8b5943.jpg"
  class="_3FLYR4bF_0">
<div class="_36ChpWj4_0">
  <div class="_2zFoi7sd_0"><span>LH</span>
  </div>
  <div class="_2_QraFYR_0">未知类型的错误真的感觉不太友好</div>
  <div class="_10o3OAxT_0">
    <p class="_3KxQPN3V_0">作者回复: 其实只是不太随大流而已。try...catch...finally的方式代码量也少不到哪里去。不过Go 2会有大幅改进的。</p>
  </div>
  <div class="_3klNVc4Z_0">
    <div class="_3Hkula0k_0">2019-03-31 23:51:42</div>
  </div>
</div>
</div>
</li>
</ul>